import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-4">
        <div className="text-sm breadcrumbs">
          <ul>
            <li>
              <a>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  className="w-4 h-4 mr-2 stroke-current"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-6l-2-2H5a2 2 0 00-2 2z"
                  ></path>
                </svg>
                Home
              </a>
            </li>
            <li>
              <a>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  className="w-4 h-4 mr-2 stroke-current"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-6l-2-2H5a2 2 0 00-2 2z"
                  ></path>
                </svg>
                Example Page
              </a>
            </li>
          </ul>
        </div>
        <h1 className="text-4xl font-bold mt-5">Table Search & Filter</h1>
        <div className=" m-5 flex gap-2">
          <div className="form-control w-full max-w-xs">
            <label className="label">
              <span className="label-text">Search</span>
            </label>
            <input
              type="text"
              placeholder="Type here"
              className="input input-bordered  input-sm w-full max-w-xs"
            />
          </div>
          <div className="form-control w-full max-w-xs">
            <label className="label">
              <span className="label-text">Filter by gender</span>
            </label>
            <select className="select select-bordered select-sm">
              <option disabled selected>
                All
              </option>
              <option>Male</option>
            </select>
          </div>
          <button className="btn align-bottom h-full btn-sm mt-9">Reset</button>
        </div>

        <div className="overflow-x-auto">
          <table className="table table-zebra w-full ">
            <thead>
              <tr>
                <th></th>
                <th>Name</th>
                <th>Job</th>
                <th>Favorite Color</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th>1</th>
                <td>Cy Ganderton</td>
                <td>Quality Control Specialist</td>
                <td>Blue</td>
              </tr>

              <tr>
                <th>2</th>
                <td>Hart Hagerty</td>
                <td>Desktop Support Technician</td>
                <td>Purple</td>
              </tr>

              <tr>
                <th>3</th>
                <td>Brice Swyre</td>
                <td>Tax Accountant</td>
                <td>Red</td>
              </tr>
            </tbody>
          </table>
        </div>
        <div className="btn-group flex w-full justify-center mt-5">
          <button className="btn btn-outline btn-sm">Prev</button>
          <button className="btn btn-sm">1</button>
          <button className="btn btn-active btn-sm">2</button>
          <button className="btn btn-sm">3</button>
          <button className="btn btn-sm">4</button>
          <button className="btn btn-outline btn-sm">Next</button>
        </div>
      </main>
    </>
  );
}
